/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import gameRules.PerguntasManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import models.Pergunta;

/**
 *
 * @author User
 */
public class Game extends javax.swing.JFrame {

    private int nivelAtual = 1;
    private Pergunta perguntaAtual;
    private PerguntasManager pm;
    private Timer timer;
    private int tempo = 30;
    
    /**
     * Creates new form Game
     */
    public Game() {
        pm = new PerguntasManager();
        initComponents();
        setLocationRelativeTo(null);
        perguntaAtual = pm.getPerguntasByNivel(nivelAtual);
        printPergunta();
        
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tempo--;
                jLabelTempoNumero.setText(Integer.toString(tempo));

                if (tempo <= 0) {
                    timer.stop();
                    JOptionPane.showMessageDialog(null, "Tempo esgotado!");
                }
            }
        });
        
        timer.start();
        
    }
    
    private void printPergunta() {
        jLabelNivelNumero.setText(Integer.toString(nivelAtual));
        jLabelTempoNumero.setText(Integer.toString(tempo));
        jLabelPergunta.setText(perguntaAtual.getPergunta());
        jButtonRespostaA.setText("A. " + perguntaAtual.getRespostas().get(0).getTexto());
        jButtonRespostaB.setText("B. " + perguntaAtual.getRespostas().get(1).getTexto());
        jButtonRespostaC.setText("C. " + perguntaAtual.getRespostas().get(2).getTexto());
        jButtonRespostaD.setText("D. " + perguntaAtual.getRespostas().get(3).getTexto());
    }
    
    private void verifyRespostaCerta(int respostaIndex) {
        if(perguntaAtual.getRespostas().get(respostaIndex).isCorreta()) {
            if(nivelAtual == 8) {
                timer.stop();
                JOptionPane.showMessageDialog(null, "PARABÉNS! VOCÊ É MILIONÁRIO");
                jButtonRespostaA.setEnabled(false);
                jButtonRespostaB.setEnabled(false);
                jButtonRespostaC.setEnabled(false);
                jButtonRespostaD.setEnabled(false);
            } else {
                tempo = 30;
                passarNivel();
            }
        } else {
            perguntaAtual = pm.getPerguntasByNivel(nivelAtual);
            printPergunta();
        }
    }
    
    private void passarNivel(){
        nivelAtual++;
        perguntaAtual = pm.getPerguntasByNivel(nivelAtual);
        printPergunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jLabelNivelNumero = new javax.swing.JLabel();
        jLabelTempo = new javax.swing.JLabel();
        jLabelTempoNumero = new javax.swing.JLabel();
        jPanelPergunta = new javax.swing.JPanel();
        jLabelPergunta = new javax.swing.JLabel();
        jButtonRespostaB = new javax.swing.JButton();
        jButtonRespostaA = new javax.swing.JButton();
        jButtonRespostaD = new javax.swing.JButton();
        jButtonRespostaC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Show do Milhão");
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNivel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNivel.setText("Nível:");

        jLabelNivelNumero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNivelNumero.setText("0");

        jLabelTempo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTempo.setText("Tempo:");

        jLabelTempoNumero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTempoNumero.setText("30");

        jPanelPergunta.setBackground(new java.awt.Color(204, 204, 204));

        jLabelPergunta.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPergunta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelPergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPergunta.setText("jLabel1");
        jLabelPergunta.setToolTipText("");

        javax.swing.GroupLayout jPanelPerguntaLayout = new javax.swing.GroupLayout(jPanelPergunta);
        jPanelPergunta.setLayout(jPanelPerguntaLayout);
        jPanelPerguntaLayout.setHorizontalGroup(
            jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPerguntaLayout.setVerticalGroup(
            jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonRespostaB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRespostaB.setText("jButton1");
        jButtonRespostaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespostaBActionPerformed(evt);
            }
        });

        jButtonRespostaA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRespostaA.setText("jButton1");
        jButtonRespostaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespostaAActionPerformed(evt);
            }
        });

        jButtonRespostaD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRespostaD.setText("jButton1");
        jButtonRespostaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespostaDActionPerformed(evt);
            }
        });

        jButtonRespostaC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRespostaC.setText("jButton1");
        jButtonRespostaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespostaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jButtonRespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jButtonRespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNivelNumero)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelTempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTempoNumero)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jButtonRespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRespostaD, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNivel)
                    .addComponent(jLabelNivelNumero)
                    .addComponent(jLabelTempo)
                    .addComponent(jLabelTempoNumero))
                .addGap(18, 18, 18)
                .addComponent(jPanelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRespostaD, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRespostaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespostaAActionPerformed
        verifyRespostaCerta(0);
    }//GEN-LAST:event_jButtonRespostaAActionPerformed

    private void jButtonRespostaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespostaBActionPerformed
        verifyRespostaCerta(1);
    }//GEN-LAST:event_jButtonRespostaBActionPerformed

    private void jButtonRespostaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespostaCActionPerformed
        verifyRespostaCerta(2);
    }//GEN-LAST:event_jButtonRespostaCActionPerformed

    private void jButtonRespostaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespostaDActionPerformed
        verifyRespostaCerta(3);
    }//GEN-LAST:event_jButtonRespostaDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRespostaA;
    private javax.swing.JButton jButtonRespostaB;
    private javax.swing.JButton jButtonRespostaC;
    private javax.swing.JButton jButtonRespostaD;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JLabel jLabelNivelNumero;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JLabel jLabelTempo;
    private javax.swing.JLabel jLabelTempoNumero;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPergunta;
    // End of variables declaration//GEN-END:variables
}
